# Generated by Django 5.2.14 on 2026-05-18 00:08

import django.core.validators
import django.db.models.deletion
import teams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0002_fundraisercampaign"),
        ("teams", "0002_teammembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="team",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_teams",
                to="fundraisers.fundraisercampaign",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="invite_code",
            field=models.CharField(
                default=teams.models._default_invite_code, max_length=32, unique=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="team",
            name="public_team_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(default="", max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="team_goal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_image",
            field=models.ImageField(blank=True, null=True, upload_to="teams/images/"),
        ),
        migrations.AddField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("captain", "Captain")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TeamReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_team_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_team_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
