# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymenteventlog",
            new_name="payments_pa_provide_29aacc_idx",
            old_name="payments_pay_provider_5e3c46_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payments_pa_provide_c3bda6_idx",
            old_name="payments_pay_provider_d5a4f9_idx",
        ),
    ]
