# Generated by Django 5.1.15 on 2026-08-22 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordersubscription'),
        ('payments', '0003_paymenttransaction_avs_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='uniq_confirmed_payment_per_order',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('status__in', ['confirmed', 'captured'])), fields=('order',), name='uniq_confirmed_payment_per_order'),
        ),
    ]
