# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supplier",
            new_name="suppliers_s_categor_1f6653_idx",
            old_name="suppliers_sup_category_status_idx",
        ),
        migrations.RenameIndex(
            model_name="supplierpurchaseorder",
            new_name="suppliers_s_supplie_56fc12_idx",
            old_name="suppliers_po_supplier_status_idx",
        ),
        migrations.RenameIndex(
            model_name="suppliertask",
            new_name="suppliers_s_status_fa5d74_idx",
            old_name="suppliers_task_status_due_idx",
        ),
    ]
