# Generated by Django 5.2.14 on 2026-05-20 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("fundraising", "Fundraising"),
                            ("corporate_gifts", "Corporate Gifts"),
                            ("contact", "Contact"),
                            ("faq", "FAQ"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "section_key",
                    models.SlugField(
                        help_text="Use a stable section id, e.g. hero-cta or trust-badges.",
                        max_length=80,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="site_content/"),
                ),
                ("cta_text", models.CharField(blank=True, max_length=80)),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="Use a full URL or a site path like /products/.",
                        max_length=255,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_content_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["page_key", "sort_order", "id"],
                "unique_together": {("page_key", "section_key")},
            },
        ),
    ]
