# Generated by Django 5.2.14 on 2026-05-17 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0001_initial"),
        ("organizations", "0001_initial"),
        ("sellers", "0001_initial"),
        ("teams", "0002_teammembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundraiserCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("fundraising_purpose", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("paid_out", "Paid out"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "campaign_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fundraisers/images/"
                    ),
                ),
                (
                    "campaign_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="fundraisers/banners/"
                    ),
                ),
                ("public_campaign_link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_fundraiser_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_fundraiser_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundraiser_campaigns",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sellers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fundraiser_campaigns",
                        to="sellers.sellerlink",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="fundraiser_campaigns", to="teams.team"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "campaign_name"],
            },
        ),
    ]
