# Generated by Django 5.2.14 on 2026-05-18 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0002_fundraisercampaign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraiserrequest",
            name="contact_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="contact_first_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="contact_last_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="desired_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="estimated_sellers",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="fundraising_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="goal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="org_type",
            field=models.CharField(default="school", max_length=40),
        ),
        migrations.AddField(
            model_name="fundraiserrequest",
            name="staff_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fundraiserrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fundraiser_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
