# Generated by Django 5.1.15 on 2026-05-24 14:14

import uuid

from django.db import migrations, models


def generate_invite_codes(apps, schema_editor):
    FundraiserCampaign = apps.get_model("fundraisers", "FundraiserCampaign")
    used = set()
    for campaign in FundraiserCampaign.objects.filter(invite_code=""):
        while True:
            code = uuid.uuid4().hex[:8].upper()
            if code not in used:
                used.add(code)
                campaign.invite_code = code
                campaign.save(update_fields=["invite_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0003_expand_fundraiser_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraisercampaign",
            name="invite_code",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.RunPython(generate_invite_codes, migrations.RunPython.noop),
    ]
