# Generated by Django 5.2.14 on 2026-05-17 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("admin_action", "Admin action"),
                            ("csv_upload", "CSV upload"),
                            ("payment_event", "Payment event"),
                            ("label_created", "Shipping label created"),
                            ("order_status_change", "Order status change"),
                            ("role_change", "Role change"),
                            ("security_event", "Security event"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=120)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("message", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="security_au_action_ea5119_idx",
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="security_au_target__262da2_idx",
                    ),
                ],
            },
        ),
    ]
