# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taxcalculation",
            new_name="taxes_taxca_provide_111b19_idx",
            old_name="taxes_taxc_provider_12fced_idx",
        ),
    ]
