# Generated by Django 5.2.14 on 2026-05-18 15:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="coupons_cou_coupon__23ec6d_idx",
            old_name="coupons_co_coupon__ae5a5e_idx",
        ),
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="coupons_cou_custome_cc4d32_idx",
            old_name="coupons_co_customer_5a7cda_idx",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="percent_off",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
