# Generated by Django 5.2.14 on 2026-05-22 19:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coupons",
            "0002_rename_coupons_co_coupon__ae5a5e_idx_coupons_cou_coupon__23ec6d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponredemption",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[core.validators.validate_json_dict],
            ),
        ),
    ]
