# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_org_crm_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationtask",
            new_name="organizatio_status_1b9c88_idx",
            old_name="organizations_task_status_due_idx",
        ),
    ]
