# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventoryreservation",
            new_name="inventory_i_sku_id_3a7aae_idx",
            old_name="inventory_r_sku_exp_idx",
        ),
    ]
