# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportexportlog",
            new_name="reports_rep_report__830584_idx",
            old_name="reports_rep_report__3c7e0e_idx",
        ),
    ]
