# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplies", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supply",
            new_name="supplies_su_categor_b609df_idx",
            old_name="supplies_sup_category_1d9ec7_idx",
        ),
    ]
