# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="crmactivity",
            new_name="crm_crmacti_activit_ab7945_idx",
            old_name="crm_activity_type_time_idx",
        ),
        migrations.RenameIndex(
            model_name="crmcontact",
            new_name="crm_crmcont_relatio_fd6efe_idx",
            old_name="crm_contact_status_follow_idx",
        ),
        migrations.RenameIndex(
            model_name="crmtask",
            new_name="crm_crmtask_status_2a9aae_idx",
            old_name="crm_task_status_due_idx",
        ),
    ]
