# Generated by Django 5.2.14 on 2026-05-22 19:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm",
            "0002_rename_crm_activity_type_time_idx_crm_crmacti_activit_ab7945_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmactivity",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[core.validators.validate_json_dict],
            ),
        ),
    ]
