# Generated by Django 5.2.14 on 2026-05-17 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedCartEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=25)),
                ("sms_consent", models.BooleanField(default=False)),
                ("email_unsubscribed", models.BooleanField(default=False)),
                ("sms_opted_out", models.BooleanField(default=False)),
                ("abandoned_at", models.DateTimeField(db_index=True)),
                ("last_activity_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("first_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "second_reminder_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("final_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("fundraiser_campaign", models.CharField(blank=True, max_length=120)),
                ("fundraiser_team", models.CharField(blank=True, max_length=120)),
                ("fundraiser_seller", models.CharField(blank=True, max_length=120)),
                ("recovered", models.BooleanField(default=False)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(db_index=True, default=False)),
                (
                    "close_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recovered", "Recovered"),
                            ("emptied", "Emptied"),
                            ("expired", "Expired"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_event",
                        to="cart.cart",
                    ),
                ),
                (
                    "recovered_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovered_cart_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartRecoveryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("first", "First reminder"),
                            ("second", "Second reminder"),
                            ("final", "Final reminder"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("to_value", models.CharField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.CharField(blank=True, max_length=250)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="abandoned_carts.abandonedcartevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "stage", "channel"),
                        name="unique_recovery_message_per_stage",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CartRecoveryToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("recover", "Recover cart"),
                            ("unsubscribe", "Unsubscribe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_tokens",
                        to="cart.cart",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="abandoned_carts.abandonedcartevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "expires_at"],
                        name="abandoned_c_purpose_e75e05_idx",
                    )
                ],
            },
        ),
    ]
