# Generated by Django 5.2.14 on 2026-05-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("sellers", "0002_sellerstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartattribution",
            name="seller_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_attributions",
                to="sellers.sellerstore",
            ),
        ),
    ]
