# Generated by Django 5.2.14 on 2026-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0005_shippinglabel_label_zpl"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_code", models.CharField(blank=True, max_length=50)),
                ("event_description", models.CharField(max_length=500)),
                ("event_timestamp", models.DateTimeField(db_index=True)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("raw", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shippinglabel",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
                "unique_together": {("label", "event_code", "event_timestamp")},
            },
        ),
    ]
