# Generated by Django 5.2.14 on 2026-05-17 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0002_fundraisercampaign"),
        ("orders", "0002_orderitem"),
        ("sellers", "0001_initial"),
        ("teams", "0002_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="fundraisers.fundraisercampaign",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sellers.sellerlink",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="teams.team",
            ),
        ),
    ]
