# Generated by Django 5.2.14 on 2026-05-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_campaign_order_seller_link_order_team"),
        ("sellers", "0002_sellerstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="seller_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sellers.sellerstore",
            ),
        ),
    ]
