import decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_seller_store"),
        ("fundraisers", "0002_fundraisercampaign"),
        ("teams", "0003_alter_team_options_team_campaign_team_invite_code_and_more"),
        ("sellers", "0002_sellerstore"),
        ("products", "0004_product_external_image_url_csvimportbatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename campaign → fundraiser_campaign
        migrations.RenameField(
            model_name="order",
            old_name="campaign",
            new_name="fundraiser_campaign",
        ),
        # Drop seller_link (SellerStore is the canonical attribution unit)
        migrations.RemoveField(
            model_name="order",
            name="seller_link",
        ),
        # Rename seller_store → seller
        migrations.RenameField(
            model_name="order",
            old_name="seller_store",
            new_name="seller",
        ),
        # Make customer nullable for guest checkout
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Order number (null until generated by post_save signal)
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        # Guest contact fields
        migrations.AddField(
            model_name="order",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=25),
        ),
        # Shipping address snapshot
        migrations.AddField(
            model_name="order",
            name="shipping_recipient_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(default="US", max_length=2),
        ),
        # Billing address snapshot
        migrations.AddField(
            model_name="order",
            name="billing_same_as_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_recipient_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_country",
            field=models.CharField(default="US", max_length=2),
        ),
        # Discount + payment status
        migrations.AddField(
            model_name="order",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        # Update status choices and default
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=20,
            ),
        ),
        # db_index on created_at
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # OrderItem — product FK (nullable so migration works on non-empty tables too)
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.product",
            ),
        ),
        # OrderItem — snapshot fields
        migrations.AddField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_total_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight_ounces",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=8),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="fundraiser_eligible",
            field=models.BooleanField(default=False),
        ),
    ]
