# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(max_length=180),
        ),
    ]
