# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_center"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_478247_idx",
            old_name="notificatio_user_id_2d9882_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_ef3643_idx",
            old_name="notificatio_user_id_f18561_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdeliverylog",
            new_name="notificatio_user_id_f1186a_idx",
            old_name="notifications_delivery_user_channel_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdeliverylog",
            new_name="notificatio_user_id_f21bb7_idx",
            old_name="notifications_delivery_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationevent",
            new_name="notificatio_event_t_58f16e_idx",
            old_name="notifications_event_type_created_idx",
        ),
    ]
