# Generated by Django 5.2.14 on 2026-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchaseorder",
            new_name="purchase_or_supplie_baf9ab_idx",
            old_name="purchase_orders_po_supplier_status_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaseorderitem",
            new_name="purchase_or_purchas_a4729d_idx",
            old_name="purchase_orders_item_po_idx",
        ),
        migrations.RenameIndex(
            model_name="receivingevent",
            new_name="purchase_or_purchas_f1e891_idx",
            old_name="purchase_orders_recv_po_time_idx",
        ),
    ]
