# Generated by Django 5.2.14 on 2026-05-18 15:59

import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sharelink",
            new_name="sharing_sha_link_ty_38f88f_idx",
            old_name="sharing_sha_link_ty_6971a1_idx",
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="token",
            field=models.CharField(
                db_index=True,
                default=sharing.models._default_token,
                max_length=40,
                unique=True,
            ),
        ),
    ]
