# Generated by Django 5.2.14 on 2026-05-18 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fundraisers", "0002_fundraisercampaign"),
        ("sellers", "0002_sellerstore"),
        ("teams", "0003_alter_team_options_team_campaign_team_invite_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_sellers_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show top-seller leaderboard on the public campaign page.",
                    ),
                ),
                (
                    "public_teams_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show top-team leaderboard on the public campaign page.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_settings",
                        to="fundraisers.fundraisercampaign",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("campaign_sellers", "Top Sellers in Campaign"),
                            ("campaign_teams", "Top Teams in Campaign"),
                            ("team_sellers", "Top Sellers in Team"),
                            ("all_campaigns", "Top Campaigns (Staff)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("rank", models.PositiveIntegerField()),
                ("total_sales_cents", models.PositiveIntegerField(default=0)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_units", models.PositiveIntegerField(default=0)),
                ("goal_cents", models.PositiveIntegerField(default=0)),
                ("goal_progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_rows",
                        to="fundraisers.fundraisercampaign",
                    ),
                ),
                (
                    "ranked_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranked_leaderboard_rows",
                        to="fundraisers.fundraisercampaign",
                    ),
                ),
                (
                    "ranked_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranked_leaderboard_rows",
                        to="teams.team",
                    ),
                ),
                (
                    "seller_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_rows",
                        to="sellers.sellerstore",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_rows",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "campaign", "team", "rank"],
                "indexes": [
                    models.Index(
                        fields=["scope", "campaign"],
                        name="leaderboard_scope_aff500_idx",
                    ),
                    models.Index(
                        fields=["scope", "team"], name="leaderboard_scope_766341_idx"
                    ),
                ],
            },
        ),
    ]
